###register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstname": "Pavel",
  "lastname": "Shishkin",
  "email": "Green@mail.com",
  "password": "1234",
  "role": "ADMIN"
}

###authenticate
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email": "ChakcNunChuck@gmail.com",
  "password": "555"
}
