###findById
GET http://localhost:8080/comments/5
Accept: application/json

###findNewsByNewsIdWithComments
GET http://localhost:8080/comments/news/19?page=1&size=5&sort=username,desc
Accept: application/json

###findAllByMatchingTextParams
GET http://localhost:8080/comments/params?username=dino&page=0&size=10&sort=username
Accept: application/json

###save
POST http://localhost:8080/comments
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "text": "Not bad at all :(",
  "username": "Vasiliy",
  "news_id": 20
}

###update
PUT http://localhost:8080/comments/191
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "text": "Wow, that's cool!",
  "username": "Svetlana"
}

###delete
DELETE http://localhost:8080/comments/191
Content-Type: application/json
Authorization: Bearer {{jwt_token}}
