###findById
GET http://localhost:8080/news/19
Accept: application/json

###findAll
GET http://localhost:8080/news?page=1&size=5
Accept: application/json

###findAllByMatchingTextParams
GET http://localhost:8080/news/params?text=в России&title=в россии&page=0&size=2&sort=id,desc
Accept: application/json

###save
POST http://localhost:8080/news
Content-Type: application/json

{
  "title": "Привет из Беларуси",
  "text": "Беларусь - великая страна!"
}

###update
PUT http://localhost:8080/news/21
Content-Type: application/json

{
  "title": "До свидания от Беларуси",
  "text": "Беларусь прощается с вами"
}

###delete
DELETE http://localhost:8080/news/21
Content-Type: application/json
