###findById
GET http://localhost:8080/news/19
Accept: application/json

###findAll
GET http://localhost:8080/news?page=1&size=5
Accept: application/json

###findAllByMatchingTextParams
GET http://localhost:8080/news/params?title=New s&text=The&page=0&size=2&sort=id,desc
Accept: application/json

###save
POST http://localhost:8080/news
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "Hello from Belarus",
  "text": "Belarus is a great country!"
}

###update
PUT http://localhost:8080/news/21
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "Good-bye from Belarus",
  "text": "Belarus says goodbye to you!"
}

###delete
DELETE http://localhost:8080/news/21
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt_token}}
