spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: enter your username
    password: enter your password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  profiles:
    active: dev
cache:
  algorithm: LRU
  capacity: 5
