###register
POST http://localhost:8081/users/register
Content-Type: application/json

{
  "firstname": "Pavel",
  "lastname": "Shishkin",
  "email": "Green@mail.com",
  "password": "1234",
  "role": "ADMIN"
}

###authenticate
POST http://localhost:8081/users/authenticate
Content-Type: application/json

{
  "email": "ChakcNunChuck@gmail.com",
  "password": "555"
}

###validate
POST http://localhost:8081/users/validate
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

###updateByToken
PUT http://localhost:8081/users
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "firstname": "Igor",
  "lastname": "Zavadskiy",
  "password": "987"
}

###deleteByToken
DELETE http://localhost:8081/users
Content-Type: application/json
Authorization: Bearer {{jwt_token}}
