--liquibase formatted sql

--changeset Grigoryev_Pavel:test2
INSERT INTO news (id, time, title, text, email)
VALUES (1, '2023-06-14 10:30:00', 'Breaking: Volcano erupts in Hawaii',
        'A massive volcanic eruption has occurred on the Big Island of Hawaii, spewing lava and ash into the air. The eruption was triggered by a series of earthquakes that rocked the island in the past few days. Authorities have issued evacuation orders for nearby residents and warned of possible tsunamis and landslides.',
        'reporter@news.com'),
       (2, '2023-06-14 10:35:00', 'SpaceX launches Starship SN20 to orbit',
        'SpaceX has successfully launched its Starship SN20 vehicle to orbit for the first time, marking a major milestone for the company and the future of space exploration. The Starship SN20 lifted off from Boca Chica, Texas, at 10:15 a.m. local time and reached an altitude of about 200 kilometers before performing a flip maneuver and reentering the atmosphere. The Starship SN20 then landed safely on a floating platform in the Gulf of Mexico.',
        'space@news.com'),
       (3, '2023-06-14 10:40:00', 'Apple unveils iPhone 15 with holographic display',
        'Apple has announced its latest flagship smartphone, the iPhone 15, which features a revolutionary holographic display that projects 3D images in mid-air. The iPhone 15 also boasts a faster processor, a longer battery life, and a new design that is thinner and lighter than ever. The iPhone 15 will be available in stores starting from July 1st.',
        'tech@news.com'),
       (4, '2023-06-14 10:45:00', 'World Cup kicks off in Qatar',
        'The 2023 FIFA World Cup has officially begun in Qatar, with the host nation facing Brazil in the opening match. The World Cup, which is held every four years, is the most prestigious and popular soccer tournament in the world, attracting millions of fans and viewers from around the globe. The World Cup will last for a month, with 32 teams competing for the coveted trophy.',
        'sports@news.com'),
       (5, '2023-06-14 10:50:00', 'New study reveals the secrets of longevity',
        'A new study published in the journal Nature has revealed the secrets of longevity, or how to live longer and healthier lives. The study, which involved analyzing the genomes of over 10,000 centenarians, or people who live past 100 years old, found that they share certain genetic variants that protect them from age-related diseases such as cancer, diabetes, and Alzheimer''s. The study also identified some lifestyle factors that contribute to longevity, such as eating a balanced diet, exercising regularly, and maintaining social connections.',
        'health@news.com');

SELECT setval('news_id_seq', (SELECT max(id) FROM news));

INSERT INTO comments (id, time, text, username, email, news_id)
VALUES (1, '2023-06-14 10:31:00', 'Wow! That''s scary! I hope everyone is safe!', 'LavaLover', 'lavalover@gmail.com',
        1),
       (2, '2023-06-14 10:32:00', 'I live in Hawaii and I can see the smoke from my window. It''s crazy!', 'Aloha123',
        'aloha123@yahoo.com', 1),
       (3, '2023-06-14 10:33:00',
        'This is why we need to stop global warming. Volcanoes are getting more active because of human activities.',
        'GreenPeace', 'greenpeace@outlook.com', 1),
       (4, '2023-06-14 10:34:00',
        'I wonder if this will affect the flights to Hawaii. I have a vacation planned next week.', 'TravelBug',
        'travelbug@hotmail.com', 1),
       (5, '2023-06-14 10:35:00', 'This is so cool! I wish I could see it in person!', 'VolcanoFan',
        'volcanofan@gmail.com', 1),
       (6, '2023-06-14 10:36:00', 'Wow! That''s amazing! Go SpaceX!', 'RocketMan', 'rocketman@gmail.com', 2),
       (7, '2023-06-14 10:37:00', 'This is a historic moment for humanity. Starship is the future of space travel.',
        'SpaceFan', 'spacefan@yahoo.com', 2),
       (8, '2023-06-14 10:38:00', 'I''m so proud of Elon Musk and his team. They are making history.', 'Musketeer',
        'musketeer@outlook.com', 2),
       (9, '2023-06-14 10:39:00', 'I wonder when they will send people to Mars. I would love to be one of them.',
        'MarsLover', 'marslover@hotmail.com', 2),
       (10, '2023-06-14 10:40:00', 'This is so exciting! I can''t wait to see more Starship launches!', 'SpaceXFan',
        'spacexfan@gmail.com', 2),
       (11, '2023-06-14 10:41:00', 'Wow! That''s awesome! I want an iPhone 15!', 'AppleFan', 'applefan@gmail.com', 3),
       (12, '2023-06-14 10:42:00', 'This is so cool! A holographic display? That''s like sci-fi!', 'TechLover',
        'techlover@yahoo.com', 3),
       (13, '2023-06-14 10:43:00', 'This is so lame. Apple is just copying Samsung. They have nothing new to offer.',
        'AndroidFan', 'androidfan@outlook.com', 3),
       (14, '2023-06-14 10:44:00', 'This is so expensive. Who can afford this?', 'BudgetUser', 'budgetuser@hotmail.com',
        3),
       (15, '2023-06-14 10:45:00', 'This is so unnecessary. Who needs a holographic display?', 'SimpleUser',
        'simpleuser@gmail.com', 3),
       (16, '2023-06-14 10:46:00', 'Wow! That''s awesome! I love soccer!', 'SoccerFan', 'soccerfan@gmail.com', 4),
       (17, '2023-06-14 10:47:00', 'This is so cool! I''m rooting for Brazil!', 'BrazilFan', 'brazilfan@yahoo.com', 4),
       (18, '2023-06-14 10:48:00', 'This is so lame. Qatar is a terrible host. They have no respect for human rights.',
        'HumanRights', 'humanrights@outlook.com', 4),
       (19, '2023-06-14 10:49:00', 'This is so boring. Soccer is a stupid sport.', 'SoccerHater',
        'soccerhater@hotmail.com',
        4),
       (20, '2023-06-14 10:50:00', 'This is so exciting! I can''t wait to watch the games!', 'WorldCupFan',
        'worldcupfan@gmail.com', 4),
       (21, '2023-06-14 10:51:00', 'Wow! That''s amazing! I want to live longer and healthier!', 'HealthFan',
        'healthfan@gmail.com', 5),
       (22, '2023-06-14 10:52:00', 'This is so cool! I wonder if I have the longevity genes.', 'GeneLover',
        'genelover@yahoo.com', 5),
       (23, '2023-06-14 10:53:00', 'This is so lame. Life is already too long and boring.', 'LifeHater',
        'lifehater@outlook.com', 5),
       (24, '2023-06-14 10:54:00', 'This is so scary. What if the world gets overpopulated?', 'EcoWarrior',
        'ecowarrior@hotmail.com', 5),
       (25, '2023-06-14 10:55:00', 'This is so interesting! I want to read the full study.', 'ScienceFan',
        'sciencefan@gmail.com', 5);

SELECT setval('comments_id_seq', (SELECT max(id) FROM comments));
