spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: enter your username
    password: enter your password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  profiles:
    active: dev
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 40
